allowBuilds:
  esbuild: false
  svelte-preprocess: false
minimumReleaseAgeExclude:
  - "@sveltejs/kit@2.68.0"
onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess
overrides:
  "svelte-eslint-parser>eslint-scope": "^9.0.0"
